<?php

return [
    [
        'category_title' => 'Abundance',
        'category_color' => ' btn-medany',
        'category_data' => [
            'Abundance',
            'Contribution',
            'Capability',
            'Wealth',
            'Resourceful',
            'Investing',
            'Availability',
            'Security',
        ]
    ],
    [
        'category_title' => 'Benevolence',
        'category_color' => 'btn-primary',
        'category_data' => [
            'Benevolence',
            'Accuracy',
            'philanthropy',
            'Responsibility',
            'loyalty',
            'Diligence',
            'Dedication',
            'Carefulness',
            'Justice',
            'Fairness',
            'Economy',
            'Thrift',
            'Commitment',
            'Consistency',
            'Mastery',
            'Perseverance',
            'Giving',
            'Completion',
            'Religiousness',
            'Productivity',
            'Achievement',
            'Fortitude',
            'Impact',
            'Confirmation',
            'Assurance',
            'Duty',
            'work',
            'Dependability',
            'Attentiveness',
            'Focus',
            'Keenness',
            'Watchfulness',
            'determination',
            'Decisiveness',
            'Assertiveness',
            'Cleanliness',
            'Purity',
            'Chastity',
            'youthfulness',
            'Agility',
            'Elegance',
            'Beauty',
            'Activeness',
            'System',
            'Organizing',
            'Direction',
            'Memorizing',
            'Remembrance',
            'Charity',
            'Subtlety',
            'Charming',
            'Depth',
        ]
    ],
    [
        'category_title' => 'Relationships',
        'category_color' => 'btn-success',
        'category_data' => [
            'Friendliness',
            'Love',
            'Kindness',
            'Warmth',
            'Altruism',
            'Belonging',
            'Affection',
            'Sensitivity',
            'Friendship',
            'Gentle',
            'Tenderness',
            'Intimacy',
        ]
    ],
    [
        'category_title' => 'Growth',
        'category_color' => 'btn-warning',
        'category_data' => [
            'Growth',
            'determination',
            'variety',
            'Change',
            'Innovation',
            'Discovery',
            'Awareness',
            'Uniqueness',
            'Maturity',
            'Ambition',
            'Development',
            'Imagination',
            'Inspiration',
            'Anticipation',
            'Quality',
            'Structure',
            'Learning',
            'Education',
            'Transcendence',
            'Knowledge',
            'Curiosity',
            'Excellence',
            'Brilliance',
            'Alertness',
            'Perception',
            'Attentiveness',
            'Motivation',
            'Effectiveness',
            'Variation',
            'Strangeness',
            'Desire',
            'Winning',
            'Wonder',
            // 'Motivation',
            'Creativity',
            'Flow',
            // 'Maturity',
            'Making A Difference',
            'Being the best',
            'Prosperity',
            'Renovation',
            // 'Change',
            'Cleverness',
            'Skillfulness',
            'Professional',
            'Fashion',
        ]
    ],
    [
        'category_title' => 'Leadership',
        'category_color' => 'btn-danger',
        'category_data' => [
            'Leadership',
            'Empowerment',
            'Honor',
            'Vision',
            'Authentic',
            'Dominance',
            'Efficiency',
            'Experience',
            'Confidence',
            'Significance',
            'Challenge',
            'Supremacy',
            'Heroism',
            'Control',
            'Awe',
            'Majesty',
            'Success',
            'Fierceness',
            'Rigor',
            'Strength',
            'Cunning',
            'Nerve',
            'Energy',
            'Bravery',
            'wisdom',
            'Fluency',
            'Power',
            'Logic',
        ]
    ],
    [
        'category_title' => 'Connection',
        'category_color' => 'btn-secondary',
        'category_data' => [
            'Connection',
            // 'wit',
            'Temperance',
            'Enjoyment',
            'Care',
            'Hospitality',
            'Humility',
            'Appreciation',
            'Contribution',
            'Cooperation',
            'Compassion',
            'Kindness',
            'Generosity',
            'Adventure',
            'Teamwork',
            'Sacrifice',
            'Aggressive',
            'Harmony',
            'Understanding',
            'Sharing',
            'Persuasive',
            'Humor',
            'Excitement',
            'Expressive',
            'Amusement',
            'Attractiveness',
            'Zeal',
            // 'Humor',
            'Fame',
            'Fascination',
            'Elation',
            'Respect',
            // 'Harmony',
            'Cunning',
            'Encouraging',
            'Courtesy',
            'Mysterious',
            'Introversion',
            'Vitality',
            'Congruency',
            'Modesty',
            'Solitude',
            'Simplicity',
            'Thankfulness',
        ]
    ],
    [
        'category_title' => 'Liberty',
        'category_color' => 'btn-outline-success',
        'category_data' => [
            'Liberty',
            'Resilience',
            'Independence',
            'Endurance',
            'openness',
            'Adaptability',
            'speed',
            'Agility',
            'Dignity',
            'Privacy',
        ]
    ],
    [
        'category_title' => 'Inner Peace',
        'category_color' => 'btn-outline-primary',
        'category_data' => [
            'Peace',
            'Trust',
            'Acceptance',
            'Permit',
            'Patience',
            'Love',
            'Mercy',
            'Happiness',
            'Tranquility',
            'Gratitude',
            'Delight',
            'Conviction',
            'Elation',
            'Solitude',
            'Presence',
            // 'Tranquility',
            'Virtue',
            'Soundness',
            'Contentment',
            'Spontaneity',
            'Balance',
            'Poise',
            'Relaxation',
            'Spirituality',
            'Stability',
            'Tolerance',
            // 'Conviction',
            'Humility',
            'Dignity',
            'Optimism',
            'Peace of mind',
            'convalescence',
            'Cheerfulness',
            'Giving',
            'Insightful',
            'Comfort',
            'Meekness',
            'Mellowness',
        ]
    ],
    [
        'category_title' => 'Clarity',
        'category_color' => 'btn-outline-danger',
        'category_data' => [
            'Purity',
            'Candor',
            'Clarity',
            'Integrity',
            'Originality',
            'Transparency',
            'Intuition',
            'Correctness',
            'Credibility',
            'Fidelity',
            'Articulate',
            'Certainty',
            'Realism',
        ]
    ],
];
