<?php

return [
    [
        "category_title" => "Ultimate Beliefs - Subjective and Religious",
        'category_color' => 'btn-warning ',
        "category_data" => [
            "1. I am just not good enough",
            "2. Fear of disappointing God",
            "3. Lack of faith in my own good or my own goals",
            "4. I don't contribute",
            "7. I have to be weak or submissive in order to be loved",
            "8. Always giving in to what others want",
            "9. I can't love myself or others unconditionally",
            "10. Denied food, love, and/or attention",
            "11. I always have to sacrifice myself for the greater cause",
            "12. Disconnected from my true self",
            "13. I don't remember the real me",
            "14. Too much energy into intellectual activities",
            "15. Life has to be a struggle",
            "16. If I speak the truth, I will create exactly what I am afraid of",
            "17. I can't figure it all out, I don't understand what is going on",
            "18. Feeling like I am going to give up; I can't take it any longer",
            // page 
            "19. I can't commit",
            "20. Resistant to follow my true calling or the desires of my heart",
            "21. Stuck in the pattern because there is no other way to do it",
            "22. Untrue to myself and others",
            "23. Shutting down my inspiration",
            "24. Unable to live in the present",
            "25. I am afraid to be the real me",
            "26. I always mess things up",
            "27. It is always my fault",
            "28. I release blocks of intuitive sight and wisdom",
            "29. I think I am crazy when I am actually receiving intuition",
            "30. Others will think I am crazy if I share my intuition",
            "31. My skills aren't good enough to assist others",
            "33. I can't find a way out",
            "34. I can't handle this/life/anything",
            // page 
            "35. I need my addictions; they serve me",
            "36. I need to prove myself",
            "37. I am not taking care of myself",
            "38. I am trapped in negativity",
            "39. I can't make a choice",
            "40. I can't let go of the rage",
            "41. I will never be whole/healed/complete",
            "42. I keep needing to sell myself",
            "43. Everything I do is unacceptable",
            "44. Fear of being labeled or stereotyped",
            "45. Feels like nothing is coming together",
            "46. Feeling like it is always going to be this way",
            "47. Everything has to be my way because I know best",
            "49. Not being able to move forward",
            "50. Refusing to see it any other way",
            // pgae 
            "52. Pretending like nothing is wrong",
            "53. I don't know who I am",
            "54. God is never there when I need Him",
            "55. I don't deserve to be loved or to receive light",
            "56. Lack of faith to create anything different",
            "57. No one wants me",
            "58. Lack of reasoning or common sense",
            "60. Can't keep track of time",
            "61. I am not worth it",
            "62. I don't deserve it",
            "63. God is punishing me because of my past choices",
            "64. Can't let go of the past",
            "65. My reality is too overwhelming",
            "66. I don't want to be here any longer",
            "67. I don't have anywhere to go",
            "68. I can't find/afford the help I need.",
            "69. I'm not that good at anything",
            "70. I'm not a people person",
            // pgae
            "71. I am controlled by others",
            "72. There is only one right way",
            "73. Shifting my truths and beliefs so I don't follow the crowd",
            "74. I am more intelligent than most people",
            "76. I am unable to access my intellectual ability",
            "77. I release what doesn't allow me to know and accept the truth",
            "78. If I change, I might lose myself",
            "79. The small satisfaction I get in the moment is not worth the effort",
            "80. I don't want to know the truth",
            "81. I have no insight",
            "82. I have to carry all the problems, without complaining",
            "83. My desires are not important",
            "84. Every time I make big changes in my life, something bad happens",
            "85. My life is falling apart, so I can't try something new.",
            "86. I have to fix my life before I can try something new",
            "87. I have health issues, so I can't try something new.",
            "75. I release the blocks in my mind that don't allow me to evaluate my beliefs and attitudes",
            "5. I have to keep my distance in relationships because others will trample on my emotion",
            "6. I have to change myself for others in order to be loved or lovable",
            "48. Swallowing other people's thoughts or opinions about me, or life in general",
            "59. I release whatever keeps me running old behaviors of thought and perception",
            "32. I have family DNA patterns that no longer serve my highest and greatest good",
            "51. Releasing mental thought processes that keep me stuck in old patterns",
        ]
    ],
    [
        "category_title" => "Ultimate Beliefs - Validity",
        'category_color' => 'btn-success',
        "category_data" => [
            "1. Denied food, love, and/or attention",
            "2. Severely abused/beaten/denied food, love, and attention",
            "3. Fear of being fat",
            "4. Always wear clean  white underwear",
        ]
    ],
    [
        "category_title" => "Ultimate Beliefs - Relationships",
        'category_color' => 'btn-danger',
        "category_data" => [
            "2. I have to deny my feelings",
            "3. I have co-dependent relationships",
            "4. I need my addictions; they serve me",
            "6. I am stuck in family dysfunction",
            "7. I am stuck in/can't get out of abusive relationships",
            "8. I am stuck in pain",
            "9. I have to be sad if someone else is sad",
            "10. My love is always being rejected",
            "11. Girls are just sissies",
            "12. Filled to the brim with unexpressed love",

            "14. If I speak the truth, I will create exactly what I am afraid of",
            "15. If I speak the truth, I will lose the ones I love",
            "16. Holding onto the pain so I will never allow it to happen again",
            // page 2
            "17. Other's needs are more important than mine",
            "18. Fear of looking foolish or of humiliation",
            "19. Feeling numb, blocked, removed, or disconnected",
            "20. Allowing the same experience to occur over and over",
            "21. Frustrated that not everyone is happy at the same time",
            "22. Need to control my environment and everyone around me",
            "23. I can't relate to other's pain or suffering",
            "24. Having trouble making the connection",
            "25. No one wants me",
            "26. I don't know the right people",
            "27. People don't like me",
            "28. Feeling spaced out, ungrounded, and fuzzy",
            "29. Can't be myself around my family",
            "30. I am a burden",
            "31. I am afraid to feel certain emotions",
            "32. I Have to reject myself and give you all the reasons I am not lovable",
            "33. Women are just second class citizens",
            "34. Always wear clean  white underwear",
            "35. House keeping is women's work",
            "36. I will get out of your way before you ask me to",
            "37. I am just hard to deal with",
            "38. I don't have the ability to protect myself emotionally",
            "39. I am not lovable",
            "40. Severely abused/beaten/denied food, love, and attention",
            "42. I have to change myself for others in order to be loved or lovable",
            "43. I have to be weak or submissive in order to be loved",
            "44. I can't love myself or others unconditionally",
            "45. Belief in limitation to love",
            "46. Don't know how to give and receive love",
            "47. Girls will grow up, get married and have babies. And no education",
            "48. Don't talk back to elders",
            "49. I always feel like I must give my life to make others happy",
            "50. It is not safe to feel my feelings",
            "51. Big boys don’t cry",
            "52. I can't feel too much; my emotions must be controlled",
            "53. Not safe to show my differences",
            "54. Relationships are unsafe",
            "55. My needs are not being met",
            "56. Feeling powerless to make others stop hurting",
            "57. There is no partner to meet my needs",
            "58. I won't be able to meet the needs of others",
            "59. No one owes you a living",
            "60. Girls can't do that.. Or be that...or good girls don't",
            "61. Resentment about dysfunctional tribal beliefs regarding love",
            "63. Deep grief over the loss of a loved one",
            "64. Holding onto all the emotional abuse in my life",
            // page 
            "65. Can't let love in",
            "66. Denied food, love, and/or attention",
            "67. Never hugged or touched enough",
            "68. I can't survive on my own",
            "69. I always give love, but there is never enough love for me",
            "70. I have to earn love",
            "71. Need to hang onto all my unhealed wounds",
            "1. I have/can't get rid of all the negative family and cultural expectations",
            "5. I am following family patterns in career, dress, money, and lifestyle choices",
            "13. Paying too much attention to material or external world because feelings are not safe",
            "41. I have to keep my distance in relationships because others will trample on my emotion",
            "62. Resentment about false and imitation love displayed in the media and in movies",

        ]
    ],
    [
        "category_title" => "Ultimate Beliefs - Money and Power",
        'category_color' => 'btn-medany',
        "category_data" => [
    
            "2. I can't be what I want because others won't be safe",
            "3. I can't change jobs because my dependents won't feel secure",
            "4. I have to change myself for others in order to be loved or lovable",
            "5. Shutting down my inspiration",
            "6. I am a burden",
            "7. My skills aren't good enough to assist others",
            "8. I have to sacrifice myself to please another so they can feel safe",
            "9. I have to steal other's power to survive",
            "10. It is bad to disobey environmental, and/or cultural authority",
            "11. Not safe to show my differences",
            "12. Trying to fit my mold",
            "13. Give away too much of myself in business and relationships",
            "14. False perceptions around money",
            "15. Lack of faith to create anything different",
            "16. No one wants me",
            "17. Lack of reasoning or common sense",

            // Page 2
            "18. I'm not good with money.",
            "19. I don't have a head for business.",
            "20. Only people who are good at business can be successful",
            "21. House keeping is women's work",
            "23. 'Real' work is 'hard' work.",
            "24. Honest money has to be 'hard earned'.",
            "25. I hate marketing.",
            "26. I'm not a salesperson.",
            "27. People who sell things are dishonest/sleazy.",


            "29. I just want someone to tell me what to do.",
            "30. Women are just second class citizens",
            "32. I expect criticism from others",
            "33. I am unwilling to involve myself in power",
            "34. I am stuck in poverty",

            // page 4
            "35. I have no idea how to start a business.",

            "38. I've just never been lucky like those.",
            "40. Making more money means working more hours",
            "41. I'm too busy just trying to get by/break even",
            "42. I don't want to work that hard",
            "43. I hate working.",
            "44. I hate/am bad at networking. and meeting new people",
            "45. I don't like/am not good at working with other people",
            "47. Things are fine the way they are",
            "48. I don't want to be greedy",
            "49. Girls are just sissies",
            "51. I am out of control with power",

            // page 5
            "52. There are people who need money a lot more than I d",
            "53. I'm just not good with people",
            "54. I don't want to learn anything new",
            "55. I don't like/am not good with technology",
            "56. Starting over is too hard/too much work",
            "57. I'm too old to try something new and/or be successful",
            "58. If I haven't been successful by now, I never will be",
            "59. I'm too old to work hard",
            "60. I'm not that good at anything",
            "61. I need money to make money",
            "62. I never have money",
            "64. The things I'm passionate about can't make money",
            "65. Hobbies don't pay.",
            "67. It feels wrong making money doing something I love.",
            "68. I grew up poor, so financial abundance isn't for me.",

            // Page 6
            "69. Money stresses me out.",
            "70. Money is dirty",
            "71. Rich people are greedy",
            "72. Being successful/having money changes people",
            "73. Rich people are fake",
            "74. Rich people have no morals",
            "75. Other people get rich and famous",
            "76. Having a lot of money makes you a bad person.",
            "77. I don't deserve a lot of money",
            "78. Having a lot of money is bad.",
            "80. Having money means sacrificing your integrity.",
            "81. I don't like rich people",
            "82. I just want to make enough to get by",
            "83. If I'm successful, my family/friends won't like me.",
            "84. If I make more money, I'll have that much more to lose.",
            "85. I don't need/want a lot of money",
            "86. Anything more than.... $ is too much for me.",

            // page 7
            "87. Dealing with/talking about money stresses me out.",
            "88. When I think about success, it feels like it's not meant to be.",
            "89. When it comes to work and money, I just want stability",
            "90. I'm a parent, I can't take risks",
            "91. My kids need me, so I can't start something new",
            "92. If I spend money on myself, that means less money for my kids",
            "93. It's irresponsible to take risks",
            "94. Taking risks is selfish.",
            "95. Wanting more money is selfish/ shallow",
            "96. I hate my job, but it pays the mortgage",
            "97. It feels intimidating to start a new thing",
            "98. Every time I make big changes in my life, something bad happens",
            "99. My life is falling apart, so I can't try something new.",
            "100. I have to fix my life before I can try something new",
            "101. I have health issues, so I can't try something new.",
            "103. Don't talk back to elders",
            "104. I'll start tomorrow.",
            "105. There's never enough time to finish things.",
            "106. I'm too busy.",
            "107. I wouldn't know what to do with that much money",
            "108. I don't like attention, so I'd rather just be a little bit successful.",
            "109. I just want to work at home in my pajamas everyday",
            "110. If I get what I want, I might lose it.",
            "111. If I have more money, that means other people have less",
            "112. I already have a pretty good life, why do I need more?",
            "114. If I can make , I'll be fine.",
            "115. I can't make (or have never be- fore made) more than..... $ .",
            "116. I never have enough money, so I never will.",
            "118. When I make more money, I spend more. That's just life",
            "119. I can never afford what I want",
            "120. I just need enough to pay my bills.",
            "121. Big boys don’t cry",

            "125. Work before play",
            "126. Women's work is never done",
            "127. Don't be so lazy",
            "128. Hard work never hurt anyone",
            "129. No one owes you a living",
            "131. My main priority is to preserve my family or other's needs",
            "39. Nothing I do ever works, why would this time be any different?",
            "46. I don't like working with people because I can't handle conflict",
            "50. If I speak the truth, I will create exactly what I am afraid of",
            "66. If you're having fun at work, you're not getting enough done",
            "79. When it comes to the rich and middle class, it's us against them",
            "122. Being rich is all about fancy cars and big houses, and I don't want any of that.",
            "123. I don't have a college or advanced degree, so there's only so far I can go",
            "124. Hard work pays off, is rewarding; Work hard and you deserve the best",
            "28. I just want to stick to what I'm good at, and let others handle the rest.",
            "31. Girls will grow up, get married and have babies. And no education",
            "36. Leaders are born, not made, and I've never been a great leader",
            "37. Getting rich is about being in the right place at the right time",
            "132. Can't keep track of time",
            "102. I release whatever keeps me running old behaviors of thought and perception",
            "1. I have to keep my distance in relationships because others will trample on my emotion",
            "22. To be successful and wealthy, I'd have to 'give it my all', and that's more than I want to give.",
            "63. If I try to make a living from my passion, I won't be passionate about it any more.",
            "113. I've had enough good fortune over the years already. I should let others have the rest.",
            "117. I'm of a certain cultural heritage/ race/gender/social or economic background, so there's only so far I can go.",
        ]
    ],
];
